name: CI ETL PySpark

on:
  push:
    branches: [dev, main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t manel-etl-pyspark .

      - name: Run ETL
        run: docker run --rm manel-etl-pyspark
