name: CI/CD PySpark ETL

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  # --- JOB CI ---
  ci:
    name: CI - Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PySpark job
        run: python app.py

      - name: Run tests
        run: pytest || echo "No tests found"

  # --- JOB CD ---
  cd:
    name: CD - Deploy to Databricks
    runs-on: ubuntu-latest
    needs: ci   # <-- ATTEND QUE CI SE TERMINE AVEC SUCCÈS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t manel-etl-pyspark .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag manel-etl-pyspark manel-etl/manel-etl-pyspark:latest
          docker push manel-etl/manel-etl-pyspark:latest

      - name: Configure Databricks CLI
        run: |
          mkdir -p ~/.databrickscfg
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = https://dbc-1397ac4c-6488.cloud.databricks.com" >> ~/.databrickscfg
          echo "token = ${{ secrets.TOKEN_DATABRICKS }}" >> ~/.databrickscfg

      - name: Deploy to Databricks Workspace
        run: |
          databricks workspace mkdirs /Repos/jdidimanel1987@gmail.com/etl-pyspark
          databricks workspace import -o app.py /Repos/jdidimanel1987@gmail.com/etl-pyspark/app.py
